const path = require("node:path");

const { storageRoot } = require("./paths");

const profilesRoot = path.join(storageRoot, "profiles");

// Placeholder per-profile storage quota. Tune later once real usage patterns land.
const PROFILE_STORAGE_QUOTA_BYTES = 50 * 1024 * 1024;

const MAX_NOTES_PER_PROFILE = 2000;
const MAX_NOTE_TITLE_LENGTH = 300;
const MAX_QUIZ_ATTEMPTS_PER_PROFILE = 5000;
const MAX_SCENES_PER_NOTE = 100;
const MAX_SCENE_TIME_LENGTH = 120;
const MAX_SCENE_PLACE_LENGTH = 200;
const MAX_SCENE_MOOD_LENGTH = 200;
const MAX_SCENE_THOUGHTS_LENGTH = 20 * 1024;
const MAX_SCENE_NOTES_LENGTH = 20 * 1024;
const MAX_ATTACHMENTS_PER_SCENE = 10;
const MAX_ATTACHMENT_SIZE_BYTES = 5 * 1024 * 1024; // 5MB per attachment (base64 will be ~1.33x)
const MAX_PROFILE_IMAGE_BYTES = 2 * 1024 * 1024;
const MAX_QUICK_NOTES_PER_PROFILE = 200;
const MAX_QUICK_NOTE_TEXT_LENGTH = 1000;
const MAX_QUICK_NOTE_SKY_LENGTH = 400;

const MAX_EVENTS_PER_PROFILE = 2000;
const MAX_EVENT_TITLE_LENGTH = 300;
const MAX_EVENT_NOTES_LENGTH = 20 * 1024;
const MAX_EVENT_LOCATION_LENGTH = 200;
const MAX_EVENT_COLOR_LENGTH = 32;
const MAX_EVENT_ID_LENGTH = 64;
const MAX_EVENT_REMINDER_MINUTES = 7 * 24 * 60; // one week ahead
const MAX_EVENT_SEGMENTS = 12; // time blocks per split-time event
const MAX_ATTACHMENTS_PER_EVENT = 6;
const MAX_EVENT_OCCURRENCE_OVERRIDES = 366;
const MAX_LINKS_PER_PROFILE = 200;
const MAX_ATTACHMENTS_PER_LINK = 12;
const MAX_LINK_TITLE_LENGTH = 200;
const MAX_LINK_DESCRIPTION_LENGTH = 20 * 1024;
const SHARE_TOKEN_PREFIX = "lk1";
const SHARE_SIGNED_PREFIX = "s1";
const MESSAGE_BROADCAST_PREFIX = "bc1";
const MESSAGE_DIRECT_PREFIX = "dm1";
const MAX_MESSAGES_PER_PROFILE = 500;
const MAX_FRIENDS_PER_PROFILE = 500;
const MAX_FRIEND_REQUESTS_PER_PROFILE = 200;
const MAX_BROADCASTS = 500;
const MAX_EVENT_OCCURRENCES = 1000; // per event per range query
const MAX_EVENT_RANGE_DAYS = 1100; // ~3 years of expanded occurrences
const FEED_TOKEN_PREFIX = "kbf1";
// Calendar feed subscription layers. `moon` is the four principal phases;
// `astrology` is the decan changes (sun crossing each 10° of the zodiac).
const CALENDAR_FEED_LAYERS = Object.freeze([
  "user",
  "notes",
  "holidays",
  "moon",
  "astrology"
]);
const DEFAULT_CALENDAR_FEED_LAYERS = Object.freeze(["user", "moon", "holidays"]);
// Per-calendar subscription options. Moon phases are the four principal phases;
// astrology detail picks the boundary size (10° decans, 1° steps, or sign starts).
const CALENDAR_MOON_PHASES = Object.freeze(["new", "first-quarter", "full", "last-quarter"]);
const CALENDAR_ASTROLOGY_DETAILS = Object.freeze(["decan", "degree", "sign"]);

module.exports = {
  profilesRoot,
  PROFILE_STORAGE_QUOTA_BYTES,
  MAX_NOTES_PER_PROFILE,
  MAX_NOTE_TITLE_LENGTH,
  MAX_QUIZ_ATTEMPTS_PER_PROFILE,
  MAX_SCENES_PER_NOTE,
  MAX_SCENE_TIME_LENGTH,
  MAX_SCENE_PLACE_LENGTH,
  MAX_SCENE_MOOD_LENGTH,
  MAX_SCENE_THOUGHTS_LENGTH,
  MAX_SCENE_NOTES_LENGTH,
  MAX_ATTACHMENTS_PER_SCENE,
  MAX_ATTACHMENT_SIZE_BYTES,
  MAX_PROFILE_IMAGE_BYTES,
  MAX_QUICK_NOTES_PER_PROFILE,
  MAX_QUICK_NOTE_TEXT_LENGTH,
  MAX_QUICK_NOTE_SKY_LENGTH,
  MAX_EVENTS_PER_PROFILE,
  MAX_EVENT_TITLE_LENGTH,
  MAX_EVENT_NOTES_LENGTH,
  MAX_EVENT_LOCATION_LENGTH,
  MAX_EVENT_COLOR_LENGTH,
  MAX_EVENT_ID_LENGTH,
  MAX_EVENT_REMINDER_MINUTES,
  MAX_EVENT_SEGMENTS,
  MAX_ATTACHMENTS_PER_EVENT,
  MAX_EVENT_OCCURRENCE_OVERRIDES,
  MAX_EVENT_OCCURRENCES,
  MAX_LINKS_PER_PROFILE,
  MAX_ATTACHMENTS_PER_LINK,
  MAX_LINK_TITLE_LENGTH,
  MAX_LINK_DESCRIPTION_LENGTH,
  SHARE_TOKEN_PREFIX,
  SHARE_SIGNED_PREFIX,
  MESSAGE_BROADCAST_PREFIX,
  MESSAGE_DIRECT_PREFIX,
  MAX_MESSAGES_PER_PROFILE,
  MAX_FRIENDS_PER_PROFILE,
  MAX_FRIEND_REQUESTS_PER_PROFILE,
  MAX_BROADCASTS,
  MAX_EVENT_RANGE_DAYS,
  FEED_TOKEN_PREFIX,
  CALENDAR_FEED_LAYERS,
  DEFAULT_CALENDAR_FEED_LAYERS,
  CALENDAR_MOON_PHASES,
  CALENDAR_ASTROLOGY_DETAILS
};
