const path = require("node:path");

const { storageRoot } = require("./paths");

const profilesRoot = path.join(storageRoot, "profiles");

// Placeholder per-profile storage quota. Tune later once real usage patterns land.
const PROFILE_STORAGE_QUOTA_BYTES = 50 * 1024 * 1024;

const MAX_NOTES_PER_PROFILE = 2000;
const MAX_NOTE_TITLE_LENGTH = 300;
const MAX_QUIZ_ATTEMPTS_PER_PROFILE = 5000;
const MAX_SCENES_PER_NOTE = 100;
const MAX_SCENE_TIME_LENGTH = 120;
const MAX_SCENE_PLACE_LENGTH = 200;
const MAX_SCENE_MOOD_LENGTH = 200;
const MAX_SCENE_THOUGHTS_LENGTH = 20 * 1024;
const MAX_SCENE_NOTES_LENGTH = 20 * 1024;
const MAX_ATTACHMENTS_PER_SCENE = 10;
const MAX_ATTACHMENT_SIZE_BYTES = 5 * 1024 * 1024; // 5MB per attachment (base64 will be ~1.33x)
const MAX_QUICK_NOTES_PER_PROFILE = 200;
const MAX_QUICK_NOTE_TEXT_LENGTH = 1000;
const MAX_QUICK_NOTE_SKY_LENGTH = 400;

const MAX_EVENTS_PER_PROFILE = 2000;
const MAX_EVENT_TITLE_LENGTH = 300;
const MAX_EVENT_NOTES_LENGTH = 20 * 1024;
const MAX_EVENT_LOCATION_LENGTH = 200;
const MAX_EVENT_COLOR_LENGTH = 32;
const MAX_EVENT_ID_LENGTH = 64;
const MAX_EVENT_REMINDER_MINUTES = 7 * 24 * 60; // one week ahead

module.exports = {
  profilesRoot,
  PROFILE_STORAGE_QUOTA_BYTES,
  MAX_NOTES_PER_PROFILE,
  MAX_NOTE_TITLE_LENGTH,
  MAX_QUIZ_ATTEMPTS_PER_PROFILE,
  MAX_SCENES_PER_NOTE,
  MAX_SCENE_TIME_LENGTH,
  MAX_SCENE_PLACE_LENGTH,
  MAX_SCENE_MOOD_LENGTH,
  MAX_SCENE_THOUGHTS_LENGTH,
  MAX_SCENE_NOTES_LENGTH,
  MAX_ATTACHMENTS_PER_SCENE,
  MAX_ATTACHMENT_SIZE_BYTES,
  MAX_QUICK_NOTES_PER_PROFILE,
  MAX_QUICK_NOTE_TEXT_LENGTH,
  MAX_QUICK_NOTE_SKY_LENGTH,
  MAX_EVENTS_PER_PROFILE,
  MAX_EVENT_TITLE_LENGTH,
  MAX_EVENT_NOTES_LENGTH,
  MAX_EVENT_LOCATION_LENGTH,
  MAX_EVENT_COLOR_LENGTH,
  MAX_EVENT_ID_LENGTH,
  MAX_EVENT_REMINDER_MINUTES
};
